# Generated by Django 2.1.15 on 2020-09-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(help_text='Username', max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(help_text='First name', max_length=50, null=True)),
                ('last_name', models.CharField(help_text='Last name', max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='groups', to='auth.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
